config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get '/articles', to: 'articles#index'
  get '/articles/new', to: 'articles#new'
  post '/articles', to: 'articles#create'
  get '/articles/:id/edit', to: 'articles#edit', as: :article_edit
  patch '/articles/:id', to: 'articles#update'
  delete '/articles/:id', to: 'articles#destroy'
  get '/articles/:id', to: 'articles#show', as: :article
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(params_article)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(params_article)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path, status: :see_other
  end

  private

  def params_article
    params.require(:article).permit(:title, :content)
  end

  #def set_restaurant
   # @article = Article.find(params[:id])
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |f| %>
  <%= f.label :title  %>
  <%= f.text_field :title  %>
  <%= f.label :content  %>
  <%= f.text_field :content  %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<%= render "form", restaurant: @article %>

app/views/articles/index.html.erb
<div>
<% @articles.each do |article| %>
  <h2><%= link_to article.title, article_path(article) %></h2>
  <p><%= article.content %></p>
<% end %>
</div>

app/views/articles/new.html.erb
<%= render "form", restaurant: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %> <%= link_to "update", article_edit_path(@article) %> <%= link_to "destroy", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Vous êtes sur? " } %></h1>


<p><%= @article.content %></p>


<%= link_to "Back", articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <header class="d-flex flex-wrap justify-content-between py-1 mb-3 border-bottom">
      <h5>Wikinimous</h5>
      <%= link_to "New article", articles_new_path %>
    </header>
    <%= yield %>
  </body>
</html>